import { createRouter, createWebHistory } from 'vue-router';
import { getAuth, onAuthStateChanged } from "firebase/auth";
// import HomeView from '../views/HomeView.vue'
import Home from "@/views/Home.vue"; // Adjust the import path as needed

const router = createRouter({
  history: createWebHistory(process.env.BASE_URL), // enables navigation w/out a page refresh 
  routes: [
    { path: "", component: () => import("../views/SignIn.vue") }, // Default route
    { path: "/home", component: () => import("../views/Home.vue") },
    { path: "/register", component: () => import("../views/Register.vue") },
    { path: "/sign-in", component: () => import("../views/SignIn.vue") },
    { path: "/createRecipe", component: () => import("../views/CreateRecipe.vue") },
    { path: "/GenerateRecipe", component: () => import("../views/GenerateRecipe.vue") },
    // { path: "/post", component: () => import("../views/Post.vue") },
    {
      path: '/post/:autoGeneratedID', // :id is the dynamic route parameter
      name: 'Post',
      component: () => import('../views/Post.vue'),
    },
    {
      path: '/postUpdate/:autoGeneratedID', // :id is the dynamic route parameter
      name: 'PostUpdate',
      component: () => import('../views/PostUpdate.vue'),
    },
    { 
      path: "/explore", 
      component: () => import("../views/Explore.vue"),
      meta: {
        requiresAuth: true,
      },
    },
    { path: "/profilesettings", component: () => import("../views/ProfileSettings.vue")},
    { path: "/profile", name: 'Profile', component: () => import("../views/Profile.vue")},
  ],  
});

const getCurrentUser = () => {
  return new Promise((resolve, reject) => {
    const removeListener = onAuthStateChanged (
      getAuth(),
      (user) => {
        removeListener();
        resolve(user);
      },
      reject
    );
  });
};


router.beforeEach(async(to, from, next) => {
  if (to.matched.some((record) => record.meta.requiresAuth)){
    if (await getCurrentUser()) {
      next();
  } else {
    next ("/");
  } 
  } else {
    next ();
  }
}) ;

export default router
