import { createRouter, createWebHistory } from 'vue-router';
import { getAuth, onAuthStateChanged } from "firebase/auth";
// import HomeView from '../views/HomeView.vue'
import Home from "@/views/Home.vue"; // Adjust the import path as needed
import ModifyRecipe from "@/views/ModifyRecipe.vue";

// const routes = [
//   {
//     path: '/',
//     name: 'home',
//     component: HomeView
//   },
//   {
//     path: '/about',
//     name: 'about',
//     // route level code-splitting
//     // this generates a separate chunk (about.[hash].js) for this route
//     // which is lazy-loaded when the route is visited.
//     component: () => import(/* webpackChunkName: "about" */ '../views/AboutView.vue')
//   }
// ]

const router = createRouter({
  history: createWebHistory(process.env.BASE_URL), // enables navigation w/out a page refresh 
  routes: [
    { path: "", component: () => import("../views/SignIn.vue") }, // Default route
    { path: "/home", component: () => import("../views/Home.vue") },
    { path: "/register", component: () => import("../views/Register.vue") },
    { path: "/sign-in", component: () => import("../views/SignIn.vue") },
    { path: "/createRecipe", component: () => import("../views/CreateRecipe.vue") },
    { path: "/generateRecipe", component: () => import("../views/GenerateRecipe.vue") },
    { path: "/generateImg", component: () => import("../views/generateImg_test.vue") },
    // { path: "/post", component: () => import("../views/Post.vue") },
    {
      path: '/post/:autoGeneratedID', // :id is the dynamic route parameter
      name: 'Post',
      component: () => import('../views/Post.vue'),
    },
    { 
      path: "/explore", 
      component: () => import("../views/Explore.vue"),
      meta: {
        requiresAuth: true,
      },
    },
    { path: "/profilesettings", component: () => import("../views/ProfileSettings.vue")},
    { path: "/profile", name: 'Profile', component: () => import("../views/Profile.vue")},
    { path: "/test_chatgpt", component: () => import("../views/test_chatgpt.vue")},
    {
      path: "/modify-recipe",
      name: "ModifyRecipe",
      component: ModifyRecipe,
      props: (route) => ({
        recipeDetails: route.params.recipeDetails,
      }),
    },
  ],
});

const getCurrentUser = () => {
  return new Promise((resolve, reject) => {
    const removeListener = onAuthStateChanged (
      getAuth(),
      (user) => {
        removeListener();
        resolve(user);
      },
      reject
    );
  });
};


router.beforeEach(async(to, from, next) => {
  if (to.matched.some((record) => record.meta.requiresAuth)){
    if (await getCurrentUser()) {
      next();
  } else {
    alert ("you dont have access!");
    next ("/");
  } 
  } else {
    next ();
  }
}) ;

export default router
