<template>
    <div class="recipe-details">
      <div class="recipe-image">
        <img :src="imageURL" alt="Recipe Image" />
      </div>
  
      <div class="recipe-info">
        <h1>Edit Recipe</h1>
        <form @submit.prevent="updateRecipe">
            <div class="form-group">
            <label for="image">Image:</label>
            <input type="file" id="image" @change="handleImageUpload" />
            </div>
          <div class="form-group">
            <label for="recipeName">Recipe Name:</label>
            <input type="text" id="recipeName" v-model="updatedRecipeName" class="form-control" />
          </div>
          <div class="form-group">
            <label for="creator">Creator:</label>
            <input type="text" id="creator" v-model="updatedCreator" class="form-control" disabled />
          </div>
          <div class="form-group">
            <label for="mealType">Meal Type:</label>
            <select id="mealType" v-model="updatedMealType" class="form-select">
              <option value="Breakfast">Breakfast</option>
              <option value="Brunch">Brunch</option>
              <option value="Lunch">Lunch</option>
              <option value="Dinner">Dinner</option>
              <option value="Supper">Supper</option>
            </select>
          </div>
          <div class="form-group">
            <label for="cuisineType">Cuisine Type:</label>
            <select id="cuisineType" v-model="updatedCuisineType" class="form-select">
              <option value="Chinese">Chinese</option>
              <option value="Western">Western</option>
              <option value="Italian">Italian</option>
              <option value="Japanese">Japanese</option>
              <option value="Korean">Korean</option>
            </select>
          </div>
          <div class="form-group">
            <label for="description">Description:</label>
            <textarea id="description" v-model="updatedDescription" class="form-control"></textarea>
          </div>
          <h2>Ingredients:</h2>
          <ul>
            <li v-for="(ingredient, index) in updatedIngredients" :key="index">
                <input type="text" v-model="ingredient.name" class="form-control" />
                <input type="number" v-model="ingredient.quantity" class="form-control" min="0" />
                <button type="button" @click="removeIngredient(index)" v-if="updatedIngredients.length > 1">Remove</button>
            </li>
          </ul>
          <button type="button" @click="addIngredient">Add Ingredient</button>
          <h2>Steps:</h2>
          <ol>
            <li v-for="(step, index) in updatedSteps" :key="index">
                <textarea v-model="step.description" class="form-control"></textarea>
                <button type="button" @click="removeStep(index)" v-if="updatedSteps.length > 1">Remove</button>
            </li>
          </ol>
          <button type="button" @click="addStep">Add Step</button>

          <div class="form-group">
            <button type="submit" class="btn btn-primary">Update Recipe</button>
          </div>

        </form>
      </div>
    </div>
  </template>
  
  <script setup>
import { ref, onMounted } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { getFirestore, doc, getDoc, updateDoc } from 'firebase/firestore';
import { getStorage, ref as storageRef, getDownloadURL, uploadBytesResumable, deleteObject } from 'firebase/storage';
import { getAuth } from "firebase/auth";
  

  const newImageFile = ref(null);

// ...

const handleImageUpload = (event) => {
  newImageFile.value = event.target.files[0];
};

  const route = useRoute();
  const recipeID = route.params.autoGeneratedID;
  const db = getFirestore();
  const recipeRef = doc(db, 'recipes', recipeID);
  
  const imageURL = ref('');
  const updatedRecipeName = ref('');
  const updatedCreator = ref('');
  const updatedMealType = ref('');
  const updatedCuisineType = ref('');
  const updatedDescription = ref('');
  const updatedIngredients = ref([]);
  const updatedSteps = ref([]);
  const router = useRouter();
  
  const addIngredient = () => {
  updatedIngredients.value.push({ name: '', quantity: 0 });
    };

    const removeIngredient = (index) => {
    updatedIngredients.value.splice(index, 1);
    };

    const addStep = () => {
    updatedSteps.value.push({ description: '' });
    };

    const removeStep = (index) => {
    updatedSteps.value.splice(index, 1);
    };

  onMounted(async () => {
    const storage = getStorage();
  
    try {
      const recipeSnapshot = await getDoc(recipeRef);
  
      if (recipeSnapshot.exists()) {
        const recipeData = recipeSnapshot.data();
        imageURL.value = await getRecipeImageURL(recipeData.imageId);
        updatedRecipeName.value = recipeData.name;
        updatedCreator.value = recipeData.creator;
        updatedMealType.value = recipeData.mealType;
        updatedCuisineType.value = recipeData.cuisineType;
        updatedDescription.value = recipeData.description;
        updatedIngredients.value = [...recipeData.ingredients];
        updatedSteps.value = [...recipeData.steps];
      } else {
        console.error('Recipe not found.');
      }
    } catch (error) {
      console.error('Error fetching recipe data:', error);
    }
  });
  
  async function getRecipeImageURL(imageID) {
  const storage = getStorage();
  const fileName = `recipeImages/${imageID}`;
  const storageReference = storageRef(storage, fileName);
  const url = await getDownloadURL(storageReference);
  return `${url}?timestamp=${Date.now()}`; // Add a cache-busting query parameter
}
  
  async function updateRecipe() {
  let updatedRecipe = {
    name: updatedRecipeName.value,
    creator: updatedCreator.value,
    mealType: updatedMealType.value,
    cuisineType: updatedCuisineType.value,
    description: updatedDescription.value,
    ingredients: updatedIngredients.value,
    steps: updatedSteps.value,
  };

  if (newImageFile.value) {
    const storage = getStorage();
    const recipeSnapshot = await getDoc(recipeRef);
    if (recipeSnapshot.exists()) {
      const recipeData = recipeSnapshot.data();
      const imageRef = storageRef(storage, `recipeImages/${recipeData.imageId}`);
      await deleteObject(imageRef); // Delete the old image
      await uploadBytesResumable(imageRef, newImageFile.value); // Upload the new image with the same name
    }
  }

  // Update the recipe in the database
  updateDoc(recipeRef, updatedRecipe)
    .then(() => {
      console.log('Recipe updated successfully');
      router.push(`/post/${recipeID}`); // Redirect to the updated recipe's page
    })
    .catch((error) => {
      console.error('Error updating recipe:', error);
    });
}
  </script>
  
  <style scoped>
  .recipe-details {
    display: flex;
    justify-content: center;
    align-items: center;
    flex-direction: column;
    margin: 20px;
  }
  
  .recipe-info {
    background-color: #f9f9f9;
    padding: 20px;
    border-radius: 10px;
    width: 80%;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
  }
  
  .form-group {
    margin-bottom: 10px;
  }
  
  label {
    display: block;
    font-weight: bold;
  }
  
  .form-control {
    width: 100%;
    padding: 5px;
    border: 1px solid #ccc;
    border-radius: 5px;
  }
  
  .form-select {
    width: 100%;
    padding: 5px;
    border: 1px solid #ccc;
    border-radius: 5px;
  }
  
  textarea {
    width: 100%;
    padding: 5px;
    border: 1px solid #ccc;
    border-radius: 5px;
  }
  
  button[type="button"] {
    background-color: #ff6347;
    color: #fff;
    border: none;
    padding: 5px 10px;
    border-radius: 5px;
    cursor: pointer;
    margin: 5px;
  }
  
  button[type="submit"] {
    background-color: #007bff;
    color: #fff;
    border: none;
    padding: 10px 20px;
    border-radius: 5px;
    cursor: pointer;
    margin-top: 20px;
  }
  
  .recipe-image img {
    max-width: 100%;
    border-radius: 10px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
    margin-bottom: 20px;
  }
  
  h1 {
    font-size: 24px;
    margin-bottom: 20px;
  }
  
  h2 {
    font-size: 20px;
    margin-top: 20px;
    margin-bottom: 10px;
  }
  
  ul, ol {
    padding: 0;
  }
  
  li {
    list-style: none;
    margin-bottom: 10px;
    display: flex;
    align-items: center;
  }
  
  li input[type="text"], li input[type="number"], li textarea {
    flex: 1;
  }
  
  /* You can add more styles as needed to enhance the appearance of your form */
  </style>
  