<template>
    <div class="recipe-details">
      <div class="recipe-image">
        <img :src="recipe.recipeImageURLs" alt="Recipe Image" />
      </div>
      <div class="recipe-info">
        <h1>{{ recipe.name }}</h1>
        <p>Creator: {{ recipe.creator }}</p>
        <p>Meal Type: {{ recipe.mealType }}</p>
        <p>Cuisine Type: {{ recipe.cuisineType }}</p>
        <p>Description: {{ recipe.description }}</p>
        <h2>Ingredients:</h2>
        <ul>
          <li v-for="(ingredient, index) in recipe.ingredients" :key="index">
            {{ ingredient.name }} - {{ ingredient.quantity }}
          </li>
        </ul>
        <h2>Steps:</h2>
        <ol>
          <li v-for="(step, index) in recipe.steps" :key="index">
            {{ step.description }}
          </li>
        </ol>
      </div>
    </div>
  </template>
  
  <script setup>
  import { ref, onMounted } from 'vue';
  import { useRoute } from 'vue-router';
  import { getFirestore, doc, getDoc } from 'firebase/firestore';
  import { getStorage, ref as storageRef, getDownloadURL } from 'firebase/storage';
  
  const route = useRoute();
  const recipe = ref({});
  const imageURL = ref('');
  
  onMounted(async () => {
    const db = getFirestore();
    const storage = getStorage();
  
    try {
      const recipeID = route.params.autoGeneratedID; // Get the recipeID from the route parameter
      const recipeRef = doc(db, 'recipes', recipeID); // Assuming 'recipes' is the Firestore collection name
      const recipeSnapshot = await getDoc(recipeRef);
  
      if (recipeSnapshot.exists()) {
        recipe.value = recipeSnapshot.data();
        const imageID = recipe.value.imageId; // Assuming the image ID is stored in the recipe data
        const fileName = `recipeImages/${imageID}`;
        const storageReference = storageRef(storage, fileName);
        imageURL.value = await getDownloadURL(storageReference);
      } else {
        console.error('Recipe not found.');
      }
    } catch (error) {
      console.error('Error fetching recipe data:', error);
    }
  });
  </script>
  
  <style scoped>
.recipe-details {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 20px;
}

.recipe-image {
  flex: 1;
  margin-right: 20px;
}

.recipe-info {
  flex: 2;
}

.recipe-image img {
  max-width: 100%;
  max-height: 100%;
  object-fit: cover;
}
</style>