<template>
<div class="recipe-details">
  <div class="recipe-image">
    <img :src="imageURL" alt="Recipe Image" />
  </div>

  <div class="recipeInfo container-fluid">
    <h1 class="recipeHeader d-inline-block ms-1">Edit Recipe</h1>
    <form @submit.prevent="updateRecipe">

      <div class="row mb-3 mt-2 ms-1">
        <label class="col-lg-2 col-md-12 col-form-label fw-bold">Image:</label>
        <div class="col-lg-10 col-md-12 col-sm-12">
          <input class="form-control" type="file" id="image" @change="handleImageUpload" />
        </div>
      </div>

      <div class="row mb-3 mt-2 ms-1">
        <label class="col-lg-2 col-md-12 col-form-label fw-bold">Recipe Name:</label>
        <div class="col-lg-10 col-md-12 col-sm-12">
          <input type="text" id="recipeName" v-model="updatedRecipeName" class="form-control" />
        </div>
      </div>

      <div class="row mb-3 ms-1">
        <label class="col-lg-2 col-md-12 col-form-label fw-bold">Creator:</label>
        <div class="col-lg-10 col-md-12 col-sm-12">
          <input type="text" id="creator" v-model="updatedCreator" class="form-control" disabled />
        </div>
      </div>

      <div class="row mb-3 ms-1">
        <label class="col-lg-2 col-md-12 col-form-label fw-bold">Meal Type:</label>
        <div class="col-lg-10 col-md-12 col-sm-12">
          <select id="mealType" v-model="updatedMealType" class="form-select">
            <option value="Breakfast">Breakfast</option>
            <option value="Brunch">Brunch</option>
            <option value="Lunch">Lunch</option>
            <option value="Dinner">Dinner</option>
            <option value="Supper">Supper</option>
          </select>
        </div>
      </div>

      <div class="row mb-3 ms-1">
        <label class="col-lg-2 col-md-12 col-form-label fw-bold">Cuisine Type:</label>
        <div class="col-lg-10 col-md-12 col-sm-12">
          <select id="cuisineType" v-model="updatedCuisineType" class="form-select">
            <option value="Chinese">Chinese</option>
            <option value="Western">Western</option>
            <option value="Italian">Italian</option>
            <option value="Japanese">Japanese</option>
            <option value="Korean">Korean</option>
          </select>
        </div>
      </div>

      <div class="row mb-3 ms-1">
        <label class="col-lg-2 col-md-12 col-form-label fw-bold">Description:</label>
        <div class="col-lg-10 col-md-12 col-sm-12">
          <textarea id="description" v-model="updatedDescription" class="form-control"></textarea>
        </div>
      </div>

      <h2 class="ms-1">Ingredients:</h2>
      <ul class="ms-1">
        <li v-for="(ingredient, index) in updatedIngredients" :key="index">
          <input type="text" v-model="ingredient.name" class="form-control" />
          <input type="number" v-model="ingredient.quantity" class="form-control" min="0" />
          <button type="button" @click="removeIngredient(index)" v-if="updatedIngredients.length > 1">Remove</button>
        </li>
      </ul>
      <button type="button" @click="addIngredient" class="ms-1">Add Ingredient</button>

      <h2 class="ms-1">Steps:</h2>
      <ol class="ms-1">
        <li v-for="(step, index) in updatedSteps" :key="index">
          <textarea v-model="step.description" class="form-control" :class="{ 'border-red': !step.description} " required></textarea>
          <button type="button" @click="removeStep(index)" v-if="updatedSteps.length > 1">Remove</button>
        </li>
      </ol>
      <button type="button" @click="addStep" class="ms-1">Add Step</button>

      <div class="form-group">
        <button type="submit" class="btn btn-primary ms-1">Update Recipe</button>
      </div>

      <!-- loading spinner -->
      <div class="loading-row mx-auto">
        <div class="loading-content" v-if="loading">
          <div class="loader"></div>
        </div>
      </div>
    </form>
  </div>
</div>
    
  </template>
  
  <script setup>
import { ref, onMounted } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { getFirestore, doc, getDoc, updateDoc } from 'firebase/firestore';
import { getStorage, ref as storageRef, getDownloadURL, uploadBytesResumable, deleteObject } from 'firebase/storage';
import { getAuth } from "firebase/auth";
  
  const newImageFile = ref(null);
// ...

const handleImageUpload = (event) => {
  newImageFile.value = event.target.files[0];
};

  const route = useRoute();
  const recipeID = route.params.autoGeneratedID;
  const db = getFirestore();
  const recipeRef = doc(db, 'recipes', recipeID);
  
  const imageURL = ref('');
  const updatedRecipeName = ref('');
  const updatedCreator = ref('');
  const updatedMealType = ref('');
  const updatedCuisineType = ref('');
  const updatedDescription = ref('');
  const updatedIngredients = ref([]);
  const updatedSteps = ref([]);
  const router = useRouter();
  
  const addIngredient = () => {
  updatedIngredients.value.push({ name: '', quantity: 0 });
    };

    const removeIngredient = (index) => {
    updatedIngredients.value.splice(index, 1);
    };

    const addStep = () => {
    updatedSteps.value.push({ description: '' });
    };

    const removeStep = (index) => {
    updatedSteps.value.splice(index, 1);
    };

  onMounted(async () => {
    const storage = getStorage();
  
    try {
      const recipeSnapshot = await getDoc(recipeRef);
  
      if (recipeSnapshot.exists()) {
        const recipeData = recipeSnapshot.data();
        imageURL.value = await getRecipeImageURL(recipeData.imageId);
        updatedRecipeName.value = recipeData.name;
        updatedCreator.value = recipeData.creator;
        updatedMealType.value = recipeData.mealType;
        updatedCuisineType.value = recipeData.cuisineType;
        updatedDescription.value = recipeData.description;
        updatedIngredients.value = [...recipeData.ingredients];
        updatedSteps.value = [...recipeData.steps];
      } else {
        console.error('');
      }
    } catch (error) {
      console.error('');
    }
  });
  
  async function getRecipeImageURL(imageID) {
  const storage = getStorage();
  const fileName = `recipeImages/${imageID}`;
  const storageReference = storageRef(storage, fileName);
  const url = await getDownloadURL(storageReference);
  return `${url}?timestamp=${Date.now()}`; // Add a cache-busting query parameter
}
  
  async function updateRecipe() {
    this.loading = true;
  let updatedRecipe = {
    name: updatedRecipeName.value,
    creator: updatedCreator.value,
    mealType: updatedMealType.value,
    cuisineType: updatedCuisineType.value,
    description: updatedDescription.value,
    ingredients: updatedIngredients.value,
    steps: updatedSteps.value,
  };

  if (newImageFile.value) {
    const storage = getStorage();
    const recipeSnapshot = await getDoc(recipeRef);
    if (recipeSnapshot.exists()) {
      const recipeData = recipeSnapshot.data();
      const imageRef = storageRef(storage, `recipeImages/${recipeData.imageId}`);
      await deleteObject(imageRef); // Delete the old image
      await uploadBytesResumable(imageRef, newImageFile.value); // Upload the new image with the same name
    }
  }

  // Update the recipe in the database
  updateDoc(recipeRef, updatedRecipe)
    .then(() => {
      this.loading = false;
      router.push(`/post/${recipeID}`); // Redirect to the updated recipe's page
    })
    .catch((error) => {
      this.loading = false;
      console.log('error: ', error);
    });
}
  </script>
  
  <script>
  export default {
    data() {
        return {
            loading: false,
        }
      }
    }
  </script>
  <style scoped>
.recipe-details {
  display: flex;
  justify-content: space-between;
  margin: 20px;
  margin-top: 120px;
  margin-left: 50px;
}
  
.recipe-info {
  flex: 1;
  padding: 20px;
}

.recipeInfo {
  margin-left: 20px;
}

.recipeHeader {
  margin-bottom: 20px;
  font-size: 36px;
}

.recipe-image {
  width: 70%;
  margin-right: 50px;
  margin-bottom: 50px;
}

.recipe-image img {
  width: 100%;
  max-width: 100%;
  height: auto;
  object-fit: cover;
  border-radius: 10px;
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
}

.label-value {
  margin-left: 50px;
}

@media (max-width: 1200px) {
  .recipe-details {
    flex-direction: column;
    align-items: center;
  }
}

@media (max-width: 992px) {
  .recipe-details {
    flex-direction: column;
    align-items: center;
  }
}

@media (max-width: 768px) {
  .recipe-details {
    flex-direction: column;
    align-items: center;
  }
}

@media (max-width: 576px) {
  .recipe-details {
    flex-direction: column;
    align-items: center;
  }
  .recipe-info {
    margin-top: 20px;
  }

  .recipe-image {
    width: 100%;
    margin-right: 0;
    margin-bottom: 20px;
  }

  .label-value {
    margin-left: 0;
  }
}


  .form-group {
    margin-bottom: 10px;
  }
  
  label {
    display: block;
    font-weight: bold;
  }
  
  .form-control {
    width: 100%;
    padding: 5px;
    border: 1px solid #ccc;
    border-radius: 5px;
  }
  
  .form-select {
    width: 100%;
    padding: 5px;
    border: 1px solid #ccc;
    border-radius: 5px;
  }
     /* loading spinner */
    .loading-row,
    .loading-content{
      height: 100%;
    }

    .loading-content{
      align-items: center;
      display: flex;
      justify-content: center;
    }

    .loader  {
      animation: rotate 1s infinite;  
      height: 50px;
      width: 50px;
    }

    .loader:before,
    .loader:after {   
      border-radius: 50%;
      content: '';
      display: block;
      height: 20px;  
      width: 20px;
    }
    .loader:before {
      animation: ball1 1s infinite;  
      background-color: #cb2025;
      box-shadow: 30px 0 0 #f8b334;
      margin-bottom: 10px;
    }
    .loader:after {
      animation: ball2 1s infinite; 
      background-color: #00a096;
      box-shadow: 30px 0 0 #97bf0d;
    }
      /* Additional Styles */
      /* Adjust styles as needed for your specific design */
      .row {
        margin-bottom: 20px;
      }


    @keyframes rotate {
      0% { 
        -webkit-transform: rotate(0deg) scale(0.8); 
        -moz-transform: rotate(0deg) scale(0.8);
      }
      50% { 
        -webkit-transform: rotate(360deg) scale(1.2); 
        -moz-transform: rotate(360deg) scale(1.2);
      }
      100% { 
        -webkit-transform: rotate(720deg) scale(0.8); 
        -moz-transform: rotate(720deg) scale(0.8);
      }
    }

    @keyframes ball1 {
      0% {
        box-shadow: 30px 0 0 #f8b334;
      }
      50% {
        box-shadow: 0 0 0 #f8b334;
        margin-bottom: 0;
        -webkit-transform: translate(15px,15px);
        -moz-transform: translate(15px, 15px);
      }
      100% {
        box-shadow: 30px 0 0 #f8b334;
        margin-bottom: 10px;
      }
    }

    @keyframes ball2 {
      0% {
        box-shadow: 30px 0 0 #97bf0d;
      }
      50% {
        box-shadow: 0 0 0 #97bf0d;
        margin-top: -20px;
        -webkit-transform: translate(15px,15px);
        -moz-transform: translate(15px, 15px);
      }
      100% {
        box-shadow: 30px 0 0 #97bf0d;
        margin-top: 0;
      }
    }
  textarea {
    width: 100%;
    padding: 5px;
    border: 1px solid #ccc;
    border-radius: 5px;
  }
  
  button[type="button"] {
    background-color: #ff6347;
    color: #fff;
    border: none;
    padding: 5px 10px;
    border-radius: 5px;
    cursor: pointer;
    margin: 5px;
  }
  
  button[type="submit"] {
    background-color: #007bff;
    color: #fff;
    border: none;
    padding: 10px 20px;
    border-radius: 5px;
    cursor: pointer;
    margin-top: 20px;
  }
  
  h1 {
    font-size: 24px;
    margin-bottom: 20px;
  }
  
  h2 {
    font-size: 20px;
    margin-top: 20px;
    margin-bottom: 10px;
  }
  
  ul, ol {
    padding: 0;
  }
  
  li {
    list-style: none;
    margin-bottom: 10px;
    display: flex;
    align-items: center;
  }
  
  li input[type="text"], li input[type="number"], li textarea {
    flex: 1;
  }
  
  /* You can add more styles as needed to enhance the appearance of your form */
  </style>
  