<template>
  <div class="recipe-card">
    <img :src="recipe.recipeImageURLs" class="card-img-top" alt="Recipe Image">
    <div class="card-body">
      <h5 class="card-title">{{ recipe.name }}</h5>
      <p class="card-creator">{{ recipe.creator }}</p>
      <router-link :to="'/post/' + recipe.autoGeneratedID" class="view-more-button">View More</router-link>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    recipe: Object,
  },
};
</script>

<style scoped>
.recipe-card {
  background-color: #fff;
  border: 1px solid #e0e0e0;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  transition: transform 0.2s;
  overflow: hidden;
  cursor: pointer;
  margin: 10px;
  display: flex;
  flex-direction: column;
  height: 100%; /* Ensure the card takes the full height */
}

.recipe-card:hover {
  transform: translateY(-5px);
}

.card-img-top {
  width: 100%;
  height: 200px;
  object-fit: cover;
}

.card-body {
  padding: 20px;
  text-align: center;
  flex: 1; /* Make the card body expand to fill the remaining space */
  display: flex;
  flex-direction: column;
  justify-content: space-between; /* Space between title and creator */
}

.card-title {
  font-size: 1.25rem;
  font-weight: bold;
  color: #333; /* Dark text color */
  margin: 0;
}

.card-creator {
  color: #555;
  margin: 10px 0;
}

.view-more-button {
  background-color: #00563D;
  color: #fff;
  border: none;
  border-radius: 20px;
  padding: 10px 20px;
  cursor: pointer;
  transition: background-color 0.3s;
  text-decoration: none;
  display: inline-block;
  font-weight: bold;
}

.view-more-button:hover {
  background-color: #003824;
}
</style>
