<template>
  <div class="recipe-card">
    <img :src="recipe.recipeImageURLs + '?timestamp=' + Date.now()" class="card-img-top" alt="Recipe Image">
    <div class="card-body">
      <h5 class="card-title">{{ recipe.name }}</h5>
      <p class="card-creator">{{ recipe.creator }}</p>
      <label for = "likeCheckBox">Like: 
        <input type = "checkbox" id = "likeCheckBox" v-model = "isChecked"  v-on:click = "increaseLikes"> 
      </label>
      <!-- Display the number of likes -->
      <p class="likes-count">Likes: {{ recipeLikes }}</p>
      <!-- Bookmark feature-->
      <label for = "bookmark">Bookmark: 
        <input type = "checkbox" id = "bookmark" v-model = "isBookmarked" v-on:click = "bookmarkRecipe">
      </label>      
      <router-link :to="'/post/' + recipe.autoGeneratedID" class="view-more-button">View More</router-link>
    </div>
  </div>
</template>

<script>
import { getFirestore, collection, addDoc, updateDoc, doc, getDoc } from 'firebase/firestore';
import { getAuth } from "firebase/auth";

export default {
  props: {
    recipe: Object,
  },

  data(){
    return{
      isChecked: false, // Initialise the checkbox state to false
      recipeLikes: 0, // Initialize number of likes
      isBookmarked: false
    }
  },

  async mounted() {
    // Retrieve the checkbox state from localStorage and set it in the data property
    try{
      const isChecked = localStorage.getItem(`like_${this.recipe.autoGeneratedID}`);
      if (isChecked) {
        this.isChecked = JSON.parse(isChecked); // Convert it from string into a Javascript object, since localstorage stores strings only
      }

      const isBookmarked = localStorage.getItem(`bookmark_${this.recipe.autoGeneratedID}`);
      if (isBookmarked){
        this.isBookmarked = JSON.parse(isBookmarked);
      }

      // Retrive likes for all recipes
      const db = getFirestore();
      // const getRecipe = await getDoc(updateRef); 
      const updateRef = doc(db, "recipes", this.recipe.autoGeneratedID); // Establish reference to recipe in DB
      const getRecipe = await getDoc(updateRef);
      if (getRecipe.exists){
        this.recipeLikes = getRecipe.data().likes;
      }
    }
    
    catch(error){
      console.log("Error message is ", + error);
    }
  },

  methods: {
    async increaseLikes(){
      this.isChecked = !this.isChecked; // Since this triggered after a toggle event, we invert it.

      // Save the checkbox state in localStorage
      localStorage.setItem(`like_${this.recipe.autoGeneratedID}`, JSON.stringify(this.isChecked)); // {RecipeID, True/False}

      // Perform your like/unlike action here
      const db = getFirestore();
      const updateRef = doc(db, "recipes", this.recipe.autoGeneratedID); // Establish reference to recipe in DB

      // Retrieve Recipe Current Likes
      const getRecipe = await getDoc(updateRef); 

      // Retrieve current likes amount
      var recipeLikes = getRecipe.data().likes; 

      // Retrieve user ID that created the recipe
      const userID = getRecipe.data().uid; 

      // Retrieve user current coins
      const userRef = doc(db, "Users", userID)
      const users = await getDoc(userRef);
      var userCoins = users.data().coins;

      // If true, means it was previously false. Increase likes
      if (this.isChecked){
        try{
          recipeLikes += 1;
          await updateDoc(updateRef, {
              likes: recipeLikes
          })

          // Update number of likes in real-time
          this.recipeLikes = recipeLikes;
          console.log(getRecipe.data().autoGeneratedID);
          console.log("Likes updated successfully")

          // Everytime recipe likes increases by 5, user gets 5 additional coins
          if (recipeLikes != 0 && recipeLikes % 5 === 0){
             userCoins += 1;
             await updateDoc(userRef, {
                coins: userCoins
             })
          }
        }
        catch(error){
          console.log("Error message is ", + error);
        }
      }

      // If false, means it was previously true. Reduce likes
      if (!this.isChecked){
        try{
          recipeLikes -= 1;
          await updateDoc(updateRef, {
              likes: recipeLikes
            })

          // Update number of likes in real-time
          this.recipeLikes = recipeLikes;
          console.log("Likes removed successfully");
        }
        catch(error){
          console.log("Error message is " + error);
        }
      }
    },

    async bookmarkRecipe(){
        this.isBookmarked = !this.isBookmarked;
        localStorage.setItem(`bookmark_${this.recipe.autoGeneratedID}`, JSON.stringify(this.isBookmarked)); // {RecipeID, True/False}

        // Perform your bookmark/un-bookmark action here
        const db = getFirestore();
        const auth = getAuth();
        const user = auth.currentUser;
        if (user){
          const userID = user.uid;
          const updateRef = doc(db, "Users", userID); // Establish reference to user in DB
          const getUser = await getDoc(updateRef); 
          const userData = getUser.data();
          if (userData && Array.isArray(userData.bookmarks)) 
          {
            if (this.isBookmarked){
              userData.bookmarks.push(this.recipe.autoGeneratedID);
              await updateDoc(updateRef, userData);
              console.log("Bookmark added successfully");
            }
            
            if (!this.isBookmarked){
              var bookmarkList = userData.bookmarks;
              var index = bookmarkList.indexOf(this.recipe.autoGeneratedID);
              if (index > -1) {
                bookmarkList.splice(index, 1);
              }
              await updateDoc(updateRef, {
                bookmarks: bookmarkList
              })
              console.log("Bookmark removed successfully");
            }
          }
          else{
            console.log("No such document!");
          }
        }
      }
    }
};
</script>

<style scoped>
.recipe-card {
  background-color: #fff;
  border: 1px solid #e0e0e0;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  transition: transform 0.2s;
  overflow: hidden;
  cursor: pointer;
  margin: 10px;
  display: flex;
  flex-direction: column;
  height: 100%; /* Ensure the card takes the full height */
}

.recipe-card:hover {
  transform: translateY(-5px);
}

.card-img-top {
  width: 100%;
  height: 200px;
  object-fit: cover;
}

.card-body {
  padding: 20px;
  text-align: center;
  flex: 1; /* Make the card body expand to fill the remaining space */
  display: flex;
  flex-direction: column;
  justify-content: space-between; /* Space between title and creator */
}

.card-title {
  font-size: 1.25rem;
  font-weight: bold;
  color: #333; /* Dark text color */
  margin: 0;
}

.card-creator {
  color: #555;
  margin: 10px 0;
}

.view-more-button {
  background-color: #00563D;
  color: #fff;
  border: none;
  border-radius: 20px;
  padding: 10px 20px;
  cursor: pointer;
  transition: background-color 0.3s;
  text-decoration: none;
  display: inline-block;
  font-weight: bold;
}

.view-more-button:hover {
  background-color: #003824;
}
</style>
